### ISSUE TITLE
엑셀파일로 명단 업데이트가 안됨

### ISSUE THREAD

**Issue by yhoonkim** [DonutWorks/Ari#446]
오늘 밤 11시에 봉사신청인데 안된다고 함 ㅜㅜ 긴급사항이니 확인 바람. 

업로드가 안되는 문제의 엑셀파일은 내 메일로 받았음 ㅜㅜ 부탁좀

**Comment by yhoonkim** [comment]
2015-03-21T10:42:26.230858+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"24/4PVF5ZXPszC5fzDUbOeVq23SzA16FHu4ne2/5xiQ=", "upload"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x007fa402800ae0 @tempfile=#<Tempfile:/tmp/RackMultipart20150321-13-fdqvbz>, @original_filename="통합 문서1.xlsx", @content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", @headers="Content-Disposition: form-data; name=\"upload[file]\"; filename=\"\xED\x86\xB5\xED\x95\xA9 \xEB\xAC\xB8\xEC\x84\x9C1.xlsx\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\r\n">}, "button"=>"", "club_id"=>"snu-habitat"}
2015-03-21T10:42:26.230622+00:00 app[web.1]: Processing by Admin::ImportController#create as HTML
2015-03-21T10:42:43.428233+00:00 heroku[router]: at=info method=POST path="/snu-habitat/admin/users/import" host=www.aritor.net request_id=f6101be0-0e7d-4f0a-b1f5-11666a018d33 fwd="110.70.53.34" dyno=web.1 connect=1ms service=18597ms status=500 bytes=1742
2015-03-21T10:42:43.423814+00:00 app[web.1]: Completed 500 Internal Server Error in 17193ms
2015-03-21T10:42:43.425149+00:00 app[web.1]:
2015-03-21T10:42:43.425161+00:00 app[web.1]:
2015-03-21T10:42:43.425156+00:00 app[web.1]:   app/controllers/admin/import_controller.rb:22:in `block in create'
2015-03-21T10:42:43.425158+00:00 app[web.1]:   app/controllers/admin/import_controller.rb:20:in `create'
2015-03-21T10:42:43.425152+00:00 app[web.1]: NoMethodError (undefined method `strip' for 2014.0:Float):
2015-03-21T10:42:43.425154+00:00 app[web.1]:   lib/user_model_normalizer.rb:14:in `normalize'
2015-03-21T10:42:43.425160+00:00 app[web.1]:

**Comment by FeGs** [comment]
데이터 클리닝 문제였다고 합니다.

**Comment by shaynekang** [comment]
수고하셨습니다. :+1:
